In [1]:
import pandas as pd

trying the pipline ex

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Age":[21,25,None,28,35,120,40,22,30,27],
    "Salary":[25000,35000,45000,None,70000,1000000,80000,30000,50000,40000],
    "City":["Pune","Mumbai","Delhi","Pune",None,"Mumbai","Delhi","Pune","Mumbai","Delhi"],
    "Education":["Bachelor","Master","Bachelor","PhD","Master","PhD","Bachelor","Master","Bachelor","PhD"],
    "Experience":[1,3,2,5,8,25,10,1,4,3],
    "Purchased":[0,0,1,1,1,0,1,0,1,1]
})

In [3]:
df

     Age     Salary    City Education  Experience  Purchased
0   21.0    25000.0    Pune  Bachelor           1          0
1   25.0    35000.0  Mumbai    Master           3          0
2    NaN    45000.0   Delhi  Bachelor           2          1
3   28.0        NaN    Pune       PhD           5          1
4   35.0    70000.0     NaN    Master           8          1
5  120.0  1000000.0  Mumbai       PhD          25          0
6   40.0    80000.0   Delhi  Bachelor          10          1
7   22.0    30000.0    Pune    Master           1          0
8   30.0    50000.0  Mumbai  Bachelor           4          1
9   27.0    40000.0   Delhi       PhD           3          1

In [4]:
import numpy as np

In [5]:
X = df.drop('Purchased', axis=1)

In [6]:
y = df['Purchased']

In [7]:
X

     Age     Salary    City Education  Experience
0   21.0    25000.0    Pune  Bachelor           1
1   25.0    35000.0  Mumbai    Master           3
2    NaN    45000.0   Delhi  Bachelor           2
3   28.0        NaN    Pune       PhD           5
4   35.0    70000.0     NaN    Master           8
5  120.0  1000000.0  Mumbai       PhD          25
6   40.0    80000.0   Delhi  Bachelor          10
7   22.0    30000.0    Pune    Master           1
8   30.0    50000.0  Mumbai  Bachelor           4
9   27.0    40000.0   Delhi       PhD           3

In [8]:
y

0    0
1    0
2    1
3    1
4    1
5    0
6    1
7    0
8    1
9    1
Name: Purchased, dtype: int64

spliting the data

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

handling the missing values

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
imputer = SimpleImputer(strategy="mean")

In [13]:
X_train[["Age", "Salary"]] = imputer.fit_transform(X_train[["Age", "Salary"]])

In [14]:
X_test[["Age", "Salary"]] = imputer.transform(X_test[["Age", "Salary"]])

encoding the variables

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
encoder = OneHotEncoder(handle_unknown="ignore")

In [37]:
encoded_train_city = encoder.fit_transform(X_train[["City"]]).toarray()

In [41]:
encoded_test_city = encoder.transform(X_test[["City"]]).toarray()

In [44]:
encoded_train_edu = encoder.fit_transform(X_train[["Education"]]).toarray()

In [46]:
encoded_test_edu = encoder.transform(X_test[["Education"]]).toarray()

In [40]:
encoded_train_city_df = pd.DataFrame(encoded_train_city, columns=encoder.get_feature_names_out())

In [42]:
encoded_test_city_df = pd.DataFrame(encoded_test_city, columns=encoder.get_feature_names_out())

In [45]:
encoded_train_edu_df = pd.DataFrame(encoded_train_edu, columns=encoder.get_feature_names_out())

In [47]:
encoded_test_edu_df = pd.DataFrame(encoded_test_edu, columns=encoder.get_feature_names_out())

In [49]:

X_train = X_train.drop('City', axis=1)

In [52]:
X_train_final = pd.concat([X_train.reset_index(drop=1), encoded_train_city_df.reset_index(drop=1)],axis =1)

In [56]:
X_train_final = X_train_final.drop('City_nan', axis=1)

In [57]:
X_train_final

,Age,Salary,Education,Experience,City_Delhi,City_Mumbai,City_Pune
0,120.000000,1000000.000000,PhD,25,0.0,1.0,0.0
1,21.000000,25000.000000,Bachelor,1,0.0,0.0,1.0
2,22.000000,30000.000000,Master,1,0.0,0.0,1.0
3,41.857143,45000.000000,Bachelor,2,1.0,0.0,0.0
4,27.000000,40000.000000,PhD,3,1.0,0.0,0.0
5,35.000000,70000.000000,Master,8,0.0,0.0,0.0
6,28.000000,184285.714286,PhD,5,0.0,0.0,1.0
7,40.000000,80000.000000,Bachelor,10,1.0,0.0,0.0

In [58]:
X_train_final = X_train_final.drop('Education', axis=1)

In [59]:
X_train_final = pd.concat([X_train_final.reset_index(drop=1), encoded_train_edu_df.reset_index(drop=1)], axis = 1)

In [60]:
X_train_final

,Age,Salary,Experience,City_Delhi,City_Mumbai,City_Pune,Education_Bachelor,Education_Master,Education_PhD
0,120.000000,1000000.000000,25,0.0,1.0,0.0,0.0,0.0,1.0
1,21.000000,25000.000000,1,0.0,0.0,1.0,1.0,0.0,0.0
2,22.000000,30000.000000,1,0.0,0.0,1.0,0.0,1.0,0.0
3,41.857143,45000.000000,2,1.0,0.0,0.0,1.0,0.0,0.0
4,27.000000,40000.000000,3,1.0,0.0,0.0,0.0,0.0,1.0
5,35.000000,70000.000000,8,0.0,0.0,0.0,0.0,1.0,0.0
6,28.000000,184285.714286,5,0.0,0.0,1.0,0.0,0.0,1.0
7,40.000000,80000.000000,10,1.0,0.0,0.0,1.0,0.0,0.0

In [62]:
X_test = X_test.drop(["City", "Education"], axis= 1)

In [63]:
X_test_final = pd.concat([X_test.reset_index(drop=1), encoded_test_city_df.reset_index(drop=1), encoded_test_edu_df.reset_index(drop=1)], axis = 1)

In [65]:
X_test_final.drop("City_nan", axis=1)

,Age,Salary,Experience,City_Delhi,City_Mumbai,City_Pune,Education_Bachelor,Education_Master,Education_PhD
0,30.0,50000.0,4,0.0,1.0,0.0,1.0,0.0,0.0
1,25.0,35000.0,3,0.0,1.0,0.0,0.0,1.0,0.0

scaling the features

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
scaler = StandardScaler()

In [69]:
X_train_final[["Age", "Salary", "Experience"]] = scaler.fit_transform(X_train_final[["Age", "Salary", "Experience"]])

In [78]:
X_test_final[["Age", "Salary", "Experience"]] = scaler.transform(X_test_final[["Age", "Salary", "Experience"]])

In [79]:
X_train_final

,Age,Salary,Experience,City_Delhi,City_Mumbai,City_Pune,Education_Bachelor,Education_Master,Education_PhD
0,2.569520e+00,2.614520,2.414321,0.0,1.0,0.0,0.0,0.0,1.0
1,-6.858316e-01,-0.510541,-0.782573,0.0,0.0,1.0,1.0,0.0,0.0
2,-6.529493e-01,-0.494515,-0.782573,0.0,0.0,1.0,0.0,1.0,0.0
3,-9.486518e-17,-0.446437,-0.649369,1.0,0.0,0.0,1.0,0.0,0.0
4,-4.885376e-01,-0.462463,-0.516165,1.0,0.0,0.0,0.0,0.0,1.0
5,-2.254789e-01,-0.366308,0.149854,0.0,0.0,0.0,0.0,1.0,0.0
6,-4.556552e-01,0.000000,-0.249757,0.0,0.0,1.0,0.0,0.0,1.0
7,-6.106720e-02,-0.334256,0.416262,1.0,0.0,0.0,1.0,0.0,0.0

In [80]:
X_test_final

,Age,Salary,Experience,City_Delhi,City_Mumbai,City_Pune,City_nan,Education_Bachelor,Education_Master,Education_PhD
0,30.0,50000.0,-1.044557,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,25.0,35000.0,-1.046920,0.0,1.0,0.0,0.0,0.0,1.0,0.0

    run the model

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
model = LinearRegression()

In [4]:
model.fit(X_train_final, y_train)

NameError: name 'X_train_final' is not defined

In [5]:
y_pred = model.predict(X_test_final)

NameError: name 'X_test_final' is not defined