creating the dataset

In [124]:
import pandas as pd

df = pd.DataFrame({
    "Age": [24, 29, None, 41, 35, 55, 31, 27, 120, 38, 30, None],
    "MonthlyIncome": [25000, 40000, 35000, None, 60000, 1000000, 45000, 30000, 70000, 52000, None, 48000],
    "YearsAtCompany": [1, 3, 2, 10, 7, 35, 4, 2, 15, 9, 5, 6],
    "Department": [
        "Sales", "HR", "IT", "Finance",
        None, "IT", "Sales", "Marketing",
        "Finance", "HR", "Marketing", "Sales"
    ],
    "JobLevel": [
        "Junior", "Mid", "Junior", "Senior",
        "Mid", "Senior", "Mid", "Junior",
        "Senior", "Mid", "Junior", "Senior"
    ],
    "RemoteWork": [
        "Yes", "No", "Yes", "No",
        "Yes", "No", "Yes", "No",
        "Yes", "No", "Yes", "No"
    ],
    "Attrition": [0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1]
})

In [125]:
df

,Age,MonthlyIncome,YearsAtCompany,Department,JobLevel,RemoteWork,Attrition
0,24.0,25000.0,1,Sales,Junior,Yes,0
1,29.0,40000.0,3,HR,Mid,No,0
2,NaN,35000.0,2,IT,Junior,Yes,1
3,41.0,NaN,10,Finance,Senior,No,0
4,35.0,60000.0,7,NaN,Mid,Yes,1
5,55.0,1000000.0,35,IT,Senior,No,1
6,31.0,45000.0,4,Sales,Mid,Yes,0
7,27.0,30000.0,2,Marketing,Junior,No,1
8,120.0,70000.0,15,Finance,Senior,Yes,0
9,38.0,52000.0,9,HR,Mid,No,0
10,30.0,NaN,5,Marketing,Junior,Yes,1
11,NaN,48000.0,6,Sales,Senior,No,1

spliting in the parts

In [126]:
X = df.drop('Attrition', axis = 1)

In [127]:
y = df['Attrition']

In [128]:
X

      Age  MonthlyIncome  YearsAtCompany Department JobLevel RemoteWork
0    24.0        25000.0               1      Sales   Junior        Yes
1    29.0        40000.0               3         HR      Mid         No
2     NaN        35000.0               2         IT   Junior        Yes
3    41.0            NaN              10    Finance   Senior         No
4    35.0        60000.0               7        NaN      Mid        Yes
5    55.0      1000000.0              35         IT   Senior         No
6    31.0        45000.0               4      Sales      Mid        Yes
7    27.0        30000.0               2  Marketing   Junior         No
8   120.0        70000.0              15    Finance   Senior        Yes
9    38.0        52000.0               9         HR      Mid         No
10   30.0            NaN               5  Marketing   Junior        Yes
11    NaN        48000.0               6      Sales   Senior         No

In [129]:
y

0     0
1     0
2     1
3     0
4     1
5     1
6     0
7     1
8     0
9     0
10    1
11    1
Name: Attrition, dtype: int64

In [130]:
from  sklearn.model_selection import train_test_split

In [131]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

impute use to remove na values

In [132]:
from sklearn.impute import SimpleImputer

In [133]:
imputer = SimpleImputer(strategy="mean")

In [134]:
X_train[['Age', 'MonthlyIncome']] = imputer.fit_transform(X_train[['Age', 'MonthlyIncome']])

In [135]:
X_test[['Age', 'MonthlyIncome']] = imputer.transform(X_test[['Age', 'MonthlyIncome']])

outlier detect

In [136]:
#Q1 = X_train['Age'].quantile(0.25)

In [137]:
#Q3 = X_train['Age'].quantile(0.75)

In [138]:
#IQR = Q3 - Q1

In [139]:
#lower = Q1 - 1.5*IQR

In [140]:
#upper = Q3 + 1.5*IQR

In [141]:
#outliers = df[(df['Age'] <= lower) | (df['Age'] >= upper)]

In [142]:
#outliers

In [143]:
#X_train = X_train[(X_train['Age'] > lower) | (X_train['Age'] < upper)]

In [144]:
#X_train

In [145]:
cols = ['Age', 'MonthlyIncome', 'YearsAtCompany']

In [146]:
for i in cols: 
    Q1 = X_train[i].quantile(0.25)
    Q3 = X_train[i].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    X_train = X_train[(X_train[i] > lower) & (X_train[i] < upper)]

In [147]:
X_train

          Age  MonthlyIncome  YearsAtCompany Department JobLevel RemoteWork
2   48.285714        35000.0               2         IT   Junior        Yes
1   29.000000        40000.0               3         HR      Mid         No
11  48.285714        48000.0               6      Sales   Senior         No
4   35.000000        60000.0               7        NaN      Mid        Yes
7   27.000000        30000.0               2  Marketing   Junior         No
6   31.000000        45000.0               4      Sales      Mid        Yes

In [148]:
X_test

     Age  MonthlyIncome  YearsAtCompany Department JobLevel RemoteWork
10  30.0       166000.0               5  Marketing   Junior        Yes
9   38.0        52000.0               9         HR      Mid         No
0   24.0        25000.0               1      Sales   Junior        Yes

encoding

In [149]:
from sklearn.preprocessing import OneHotEncoder

In [153]:
encoder_train = OneHotEncoder(handle_unknown='')

In [154]:
encoder_train.fit_transform(X)

InvalidParameterError: The 'handle_unknown' parameter of OneHotEncoder must be a str among {'infrequent_if_exist', 'warn', 'ignore', 'error'}. Got '%killbgscripts' instead.