In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
ls

 encoding.csv   'jun 15.ipynb'  'jun 18.ipynb'   test.csv          venv/
 flie.csv       'jun 16.ipynb'   mel.zip         Untitled3.ipynb
'jun 14.ipynb'  'jun 17.ipynb'   outliers.csv    Untitled.ipynb

In [4]:
#encoding

In [5]:
df = pd.read_csv("encoding.csv")

In [6]:
df

   Age  Salary    City  Gender  Purchased
0   20   30000    Pune    Male          0
1   22   40000  Mumbai  Female          1
2   25   45000   Delhi    Male          0
3   25   50000    Pune    Male          1
4   27   50000    Pune  Female          1
5   30   55000   Delhi    Male          1
6   25   60000    Pune  Female          1

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
df['Age'] = LabelEncoder().fit_transform(df['Age'])

In [13]:
df

   Age  Salary    City  Gender  Purchased
0    0   30000    Pune    Male          0
1    1   40000  Mumbai  Female          1
2    2   45000   Delhi    Male          0
3    2   50000    Pune    Male          1
4    3   50000    Pune  Female          1
5    4   55000   Delhi    Male          1
6    2   60000    Pune  Female          1

In [16]:
df = pd.get_dummies(df, columns=['City'])

In [17]:
df

   Age  Salary  Gender  Purchased  City_Delhi  City_Mumbai  City_Pune
0    0   30000    Male          0       False        False       True
1    1   40000  Female          1       False         True      False
2    2   45000    Male          0        True        False      False
3    2   50000    Male          1       False        False       True
4    3   50000  Female          1       False        False       True
5    4   55000    Male          1        True        False      False
6    2   60000  Female          1       False        False       True

In [20]:
df1 = pd.read_csv('encoding.csv')

In [26]:
pd.get_dummies(df1, columns=['City'], drop_first = True)

   Age  Salary  Gender  Purchased  City_Mumbai  City_Pune
0   20   30000    Male          0        False       True
1   22   40000  Female          1         True      False
2   25   45000    Male          0        False      False
3   25   50000    Male          1        False       True
4   27   50000  Female          1        False       True
5   30   55000    Male          1        False      False
6   25   60000  Female          1        False       True